package com.bordero.client.domain.model;

public enum DocumentType {
    CONTRATO_SOCIAL,
    CARTAO_CNPJ,
    COMPROVANTE_ENDERECO,
    BALANCO_PATRIMONIAL,
    DRE,
    CERTIDAO_NEGATIVA_FEDERAL,
    CERTIDAO_NEGATIVA_ESTADUAL,
    CERTIDAO_NEGATIVA_MUNICIPAL,
    DOCUMENTO_SOCIO_RG,
    DOCUMENTO_SOCIO_CPF
}
